# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

services:
    #CRUD Category
    admin.category:
        class: AdminBundle\Admin\CategoryAdmin
        arguments: [~, AdminBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
    #CRUD SubCategory
    admin.subcategory:
        class: AdminBundle\Admin\SubcategoryAdmin
        arguments: [~, AdminBundle\Entity\Subcategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Subcategory}
    #CRUD Product
    admin.product:
        class: AdminBundle\Admin\ProductAdmin
        arguments: [~, AdminBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Product}